/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZodiacRouteImport } from './routes/zodiac'
import { Route as WallpaperRouteImport } from './routes/wallpaper'
import { Route as VirtualShrineRouteImport } from './routes/virtual-shrine'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TarotRouteImport } from './routes/tarot'
import { Route as TaiSuiRouteImport } from './routes/tai-sui'
import { Route as SiamsiRouteImport } from './routes/siamsi'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlateAnalysisRouteImport } from './routes/plate-analysis'
import { Route as PhoneAnalysisRouteImport } from './routes/phone-analysis'
import { Route as NamingRouteImport } from './routes/naming'
import { Route as NameAnalysisRouteImport } from './routes/name-analysis'
import { Route as LuckyColorsRouteImport } from './routes/lucky-colors'
import { Route as LoveCompatibilityRouteImport } from './routes/love-compatibility'
import { Route as LotteryRouteImport } from './routes/lottery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LifeGraphRouteImport } from './routes/life-graph'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DreamRouteImport } from './routes/dream'
import { Route as DestinyCardgRouteImport } from './routes/destiny-cardg'
import { Route as DestinyCardRouteImport } from './routes/destiny-card'
import { Route as DailyHubRouteImport } from './routes/daily-hub'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrahmaWheelRouteImport } from './routes/brahma-wheel'
import { Route as BaziRouteImport } from './routes/bazi'
import { Route as AuspiciousCalendarRouteImport } from './routes/auspicious-calendar'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TarotIndexRouteImport } from './routes/tarot.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as DreamIndexRouteImport } from './routes/dream.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TarotTypeRouteImport } from './routes/tarot.$type'
import { Route as ProfileSettingsRouteImport } from './routes/profile.settings'
import { Route as ProfileHistoryRouteImport } from './routes/profile.history'
import { Route as DreamSlugRouteImport } from './routes/dream.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ApiUserSessionRouteImport } from './routes/api.user-session'
import { Route as ApiUserRegisterRouteImport } from './routes/api.user-register'
import { Route as ApiUserLoginRouteImport } from './routes/api.user-login'
import { Route as ApiSiteContentRouteImport } from './routes/api.site-content'
import { Route as ApiReadingHistoryRouteImport } from './routes/api.reading-history'
import { Route as ApiLotteryRouteImport } from './routes/api.lottery'
import { Route as ApiLeadsRouteImport } from './routes/api.leads'
import { Route as ApiFaqsRouteImport } from './routes/api.faqs'
import { Route as ApiDreamsRouteImport } from './routes/api.dreams'
import { Route as ApiDashboardRouteImport } from './routes/api.dashboard'
import { Route as ApiCronAutoArticleRouteImport } from './routes/api.cron-auto-article'
import { Route as ApiContactMessagesRouteImport } from './routes/api.contact-messages'
import { Route as ApiAutoArticleRouteImport } from './routes/api.auto-article'
import { Route as ApiAuditEventsRouteImport } from './routes/api.audit-events'
import { Route as ApiArticlesRouteImport } from './routes/api.articles'
import { Route as ApiAdminUsersRouteImport } from './routes/api.admin-users'
import { Route as ApiAdminSessionRouteImport } from './routes/api.admin-session'
import { Route as ApiAdminLoginRouteImport } from './routes/api.admin-login'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminHelpRouteImport } from './routes/admin.help'
import { Route as AdminDreamsRouteImport } from './routes/admin.dreams'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'

const ZodiacRoute = ZodiacRouteImport.update({
  id: '/zodiac',
  path: '/zodiac',
  getParentRoute: () => rootRouteImport,
} as any)
const WallpaperRoute = WallpaperRouteImport.update({
  id: '/wallpaper',
  path: '/wallpaper',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualShrineRoute = VirtualShrineRouteImport.update({
  id: '/virtual-shrine',
  path: '/virtual-shrine',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotRoute = TarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiSuiRoute = TaiSuiRouteImport.update({
  id: '/tai-sui',
  path: '/tai-sui',
  getParentRoute: () => rootRouteImport,
} as any)
const SiamsiRoute = SiamsiRouteImport.update({
  id: '/siamsi',
  path: '/siamsi',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlateAnalysisRoute = PlateAnalysisRouteImport.update({
  id: '/plate-analysis',
  path: '/plate-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneAnalysisRoute = PhoneAnalysisRouteImport.update({
  id: '/phone-analysis',
  path: '/phone-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const NamingRoute = NamingRouteImport.update({
  id: '/naming',
  path: '/naming',
  getParentRoute: () => rootRouteImport,
} as any)
const NameAnalysisRoute = NameAnalysisRouteImport.update({
  id: '/name-analysis',
  path: '/name-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LuckyColorsRoute = LuckyColorsRouteImport.update({
  id: '/lucky-colors',
  path: '/lucky-colors',
  getParentRoute: () => rootRouteImport,
} as any)
const LoveCompatibilityRoute = LoveCompatibilityRouteImport.update({
  id: '/love-compatibility',
  path: '/love-compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const LotteryRoute = LotteryRouteImport.update({
  id: '/lottery',
  path: '/lottery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeGraphRoute = LifeGraphRouteImport.update({
  id: '/life-graph',
  path: '/life-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamRoute = DreamRouteImport.update({
  id: '/dream',
  path: '/dream',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinyCardgRoute = DestinyCardgRouteImport.update({
  id: '/destiny-cardg',
  path: '/destiny-cardg',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinyCardRoute = DestinyCardRouteImport.update({
  id: '/destiny-card',
  path: '/destiny-card',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyHubRoute = DailyHubRouteImport.update({
  id: '/daily-hub',
  path: '/daily-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrahmaWheelRoute = BrahmaWheelRouteImport.update({
  id: '/brahma-wheel',
  path: '/brahma-wheel',
  getParentRoute: () => rootRouteImport,
} as any)
const BaziRoute = BaziRouteImport.update({
  id: '/bazi',
  path: '/bazi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuspiciousCalendarRoute = AuspiciousCalendarRouteImport.update({
  id: '/auspicious-calendar',
  path: '/auspicious-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotIndexRoute = TarotIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TarotRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const DreamIndexRoute = DreamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DreamRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TarotTypeRoute = TarotTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => TarotRoute,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileHistoryRoute = ProfileHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProfileRoute,
} as any)
const DreamSlugRoute = DreamSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DreamRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const ApiUserSessionRoute = ApiUserSessionRouteImport.update({
  id: '/api/user-session',
  path: '/api/user-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserRegisterRoute = ApiUserRegisterRouteImport.update({
  id: '/api/user-register',
  path: '/api/user-register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserLoginRoute = ApiUserLoginRouteImport.update({
  id: '/api/user-login',
  path: '/api/user-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteContentRoute = ApiSiteContentRouteImport.update({
  id: '/api/site-content',
  path: '/api/site-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadingHistoryRoute = ApiReadingHistoryRouteImport.update({
  id: '/api/reading-history',
  path: '/api/reading-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLotteryRoute = ApiLotteryRouteImport.update({
  id: '/api/lottery',
  path: '/api/lottery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFaqsRoute = ApiFaqsRouteImport.update({
  id: '/api/faqs',
  path: '/api/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDreamsRoute = ApiDreamsRouteImport.update({
  id: '/api/dreams',
  path: '/api/dreams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronAutoArticleRoute = ApiCronAutoArticleRouteImport.update({
  id: '/api/cron-auto-article',
  path: '/api/cron-auto-article',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactMessagesRoute = ApiContactMessagesRouteImport.update({
  id: '/api/contact-messages',
  path: '/api/contact-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoArticleRoute = ApiAutoArticleRouteImport.update({
  id: '/api/auto-article',
  path: '/api/auto-article',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditEventsRoute = ApiAuditEventsRouteImport.update({
  id: '/api/audit-events',
  path: '/api/audit-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArticlesRoute = ApiArticlesRouteImport.update({
  id: '/api/articles',
  path: '/api/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin-users',
  path: '/api/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin-session',
  path: '/api/admin-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin-login',
  path: '/api/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDreamsRoute = AdminDreamsRouteImport.update({
  id: '/dreams',
  path: '/dreams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/auspicious-calendar': typeof AuspiciousCalendarRoute
  '/bazi': typeof BaziRoute
  '/brahma-wheel': typeof BrahmaWheelRoute
  '/contact': typeof ContactRoute
  '/daily-hub': typeof DailyHubRoute
  '/destiny-card': typeof DestinyCardRoute
  '/destiny-cardg': typeof DestinyCardgRoute
  '/dream': typeof DreamRouteWithChildren
  '/help': typeof HelpRoute
  '/life-graph': typeof LifeGraphRoute
  '/login': typeof LoginRoute
  '/lottery': typeof LotteryRoute
  '/love-compatibility': typeof LoveCompatibilityRoute
  '/lucky-colors': typeof LuckyColorsRoute
  '/name-analysis': typeof NameAnalysisRoute
  '/naming': typeof NamingRoute
  '/phone-analysis': typeof PhoneAnalysisRoute
  '/plate-analysis': typeof PlateAnalysisRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/siamsi': typeof SiamsiRoute
  '/tai-sui': typeof TaiSuiRoute
  '/tarot': typeof TarotRouteWithChildren
  '/terms': typeof TermsRoute
  '/virtual-shrine': typeof VirtualShrineRoute
  '/wallpaper': typeof WallpaperRoute
  '/zodiac': typeof ZodiacRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/dreams': typeof AdminDreamsRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-session': typeof ApiAdminSessionRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/articles': typeof ApiArticlesRoute
  '/api/audit-events': typeof ApiAuditEventsRoute
  '/api/auto-article': typeof ApiAutoArticleRoute
  '/api/contact-messages': typeof ApiContactMessagesRoute
  '/api/cron-auto-article': typeof ApiCronAutoArticleRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/dreams': typeof ApiDreamsRoute
  '/api/faqs': typeof ApiFaqsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/lottery': typeof ApiLotteryRoute
  '/api/reading-history': typeof ApiReadingHistoryRoute
  '/api/site-content': typeof ApiSiteContentRoute
  '/api/user-login': typeof ApiUserLoginRoute
  '/api/user-register': typeof ApiUserRegisterRoute
  '/api/user-session': typeof ApiUserSessionRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/dream/$slug': typeof DreamSlugRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/tarot/$type': typeof TarotTypeRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/dream/': typeof DreamIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/tarot/': typeof TarotIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auspicious-calendar': typeof AuspiciousCalendarRoute
  '/bazi': typeof BaziRoute
  '/brahma-wheel': typeof BrahmaWheelRoute
  '/contact': typeof ContactRoute
  '/daily-hub': typeof DailyHubRoute
  '/destiny-card': typeof DestinyCardRoute
  '/destiny-cardg': typeof DestinyCardgRoute
  '/help': typeof HelpRoute
  '/life-graph': typeof LifeGraphRoute
  '/login': typeof LoginRoute
  '/lottery': typeof LotteryRoute
  '/love-compatibility': typeof LoveCompatibilityRoute
  '/lucky-colors': typeof LuckyColorsRoute
  '/name-analysis': typeof NameAnalysisRoute
  '/naming': typeof NamingRoute
  '/phone-analysis': typeof PhoneAnalysisRoute
  '/plate-analysis': typeof PlateAnalysisRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/siamsi': typeof SiamsiRoute
  '/tai-sui': typeof TaiSuiRoute
  '/terms': typeof TermsRoute
  '/virtual-shrine': typeof VirtualShrineRoute
  '/wallpaper': typeof WallpaperRoute
  '/zodiac': typeof ZodiacRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/dreams': typeof AdminDreamsRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-session': typeof ApiAdminSessionRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/articles': typeof ApiArticlesRoute
  '/api/audit-events': typeof ApiAuditEventsRoute
  '/api/auto-article': typeof ApiAutoArticleRoute
  '/api/contact-messages': typeof ApiContactMessagesRoute
  '/api/cron-auto-article': typeof ApiCronAutoArticleRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/dreams': typeof ApiDreamsRoute
  '/api/faqs': typeof ApiFaqsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/lottery': typeof ApiLotteryRoute
  '/api/reading-history': typeof ApiReadingHistoryRoute
  '/api/site-content': typeof ApiSiteContentRoute
  '/api/user-login': typeof ApiUserLoginRoute
  '/api/user-register': typeof ApiUserRegisterRoute
  '/api/user-session': typeof ApiUserSessionRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/dream/$slug': typeof DreamSlugRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/tarot/$type': typeof TarotTypeRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/dream': typeof DreamIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/tarot': typeof TarotIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/auspicious-calendar': typeof AuspiciousCalendarRoute
  '/bazi': typeof BaziRoute
  '/brahma-wheel': typeof BrahmaWheelRoute
  '/contact': typeof ContactRoute
  '/daily-hub': typeof DailyHubRoute
  '/destiny-card': typeof DestinyCardRoute
  '/destiny-cardg': typeof DestinyCardgRoute
  '/dream': typeof DreamRouteWithChildren
  '/help': typeof HelpRoute
  '/life-graph': typeof LifeGraphRoute
  '/login': typeof LoginRoute
  '/lottery': typeof LotteryRoute
  '/love-compatibility': typeof LoveCompatibilityRoute
  '/lucky-colors': typeof LuckyColorsRoute
  '/name-analysis': typeof NameAnalysisRoute
  '/naming': typeof NamingRoute
  '/phone-analysis': typeof PhoneAnalysisRoute
  '/plate-analysis': typeof PlateAnalysisRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/siamsi': typeof SiamsiRoute
  '/tai-sui': typeof TaiSuiRoute
  '/tarot': typeof TarotRouteWithChildren
  '/terms': typeof TermsRoute
  '/virtual-shrine': typeof VirtualShrineRoute
  '/wallpaper': typeof WallpaperRoute
  '/zodiac': typeof ZodiacRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/dreams': typeof AdminDreamsRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-session': typeof ApiAdminSessionRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/articles': typeof ApiArticlesRoute
  '/api/audit-events': typeof ApiAuditEventsRoute
  '/api/auto-article': typeof ApiAutoArticleRoute
  '/api/contact-messages': typeof ApiContactMessagesRoute
  '/api/cron-auto-article': typeof ApiCronAutoArticleRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/dreams': typeof ApiDreamsRoute
  '/api/faqs': typeof ApiFaqsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/lottery': typeof ApiLotteryRoute
  '/api/reading-history': typeof ApiReadingHistoryRoute
  '/api/site-content': typeof ApiSiteContentRoute
  '/api/user-login': typeof ApiUserLoginRoute
  '/api/user-register': typeof ApiUserRegisterRoute
  '/api/user-session': typeof ApiUserSessionRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/dream/$slug': typeof DreamSlugRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/tarot/$type': typeof TarotTypeRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/dream/': typeof DreamIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/tarot/': typeof TarotIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/articles'
    | '/auspicious-calendar'
    | '/bazi'
    | '/brahma-wheel'
    | '/contact'
    | '/daily-hub'
    | '/destiny-card'
    | '/destiny-cardg'
    | '/dream'
    | '/help'
    | '/life-graph'
    | '/login'
    | '/lottery'
    | '/love-compatibility'
    | '/lucky-colors'
    | '/name-analysis'
    | '/naming'
    | '/phone-analysis'
    | '/plate-analysis'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/siamsi'
    | '/tai-sui'
    | '/tarot'
    | '/terms'
    | '/virtual-shrine'
    | '/wallpaper'
    | '/zodiac'
    | '/admin/articles'
    | '/admin/audit'
    | '/admin/contact'
    | '/admin/dreams'
    | '/admin/help'
    | '/admin/messages'
    | '/admin/users'
    | '/api/admin-login'
    | '/api/admin-session'
    | '/api/admin-users'
    | '/api/articles'
    | '/api/audit-events'
    | '/api/auto-article'
    | '/api/contact-messages'
    | '/api/cron-auto-article'
    | '/api/dashboard'
    | '/api/dreams'
    | '/api/faqs'
    | '/api/leads'
    | '/api/lottery'
    | '/api/reading-history'
    | '/api/site-content'
    | '/api/user-login'
    | '/api/user-register'
    | '/api/user-session'
    | '/articles/$slug'
    | '/dream/$slug'
    | '/profile/history'
    | '/profile/settings'
    | '/tarot/$type'
    | '/admin/'
    | '/articles/'
    | '/dream/'
    | '/profile/'
    | '/tarot/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-login'
    | '/auspicious-calendar'
    | '/bazi'
    | '/brahma-wheel'
    | '/contact'
    | '/daily-hub'
    | '/destiny-card'
    | '/destiny-cardg'
    | '/help'
    | '/life-graph'
    | '/login'
    | '/lottery'
    | '/love-compatibility'
    | '/lucky-colors'
    | '/name-analysis'
    | '/naming'
    | '/phone-analysis'
    | '/plate-analysis'
    | '/privacy'
    | '/register'
    | '/siamsi'
    | '/tai-sui'
    | '/terms'
    | '/virtual-shrine'
    | '/wallpaper'
    | '/zodiac'
    | '/admin/articles'
    | '/admin/audit'
    | '/admin/contact'
    | '/admin/dreams'
    | '/admin/help'
    | '/admin/messages'
    | '/admin/users'
    | '/api/admin-login'
    | '/api/admin-session'
    | '/api/admin-users'
    | '/api/articles'
    | '/api/audit-events'
    | '/api/auto-article'
    | '/api/contact-messages'
    | '/api/cron-auto-article'
    | '/api/dashboard'
    | '/api/dreams'
    | '/api/faqs'
    | '/api/leads'
    | '/api/lottery'
    | '/api/reading-history'
    | '/api/site-content'
    | '/api/user-login'
    | '/api/user-register'
    | '/api/user-session'
    | '/articles/$slug'
    | '/dream/$slug'
    | '/profile/history'
    | '/profile/settings'
    | '/tarot/$type'
    | '/admin'
    | '/articles'
    | '/dream'
    | '/profile'
    | '/tarot'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/articles'
    | '/auspicious-calendar'
    | '/bazi'
    | '/brahma-wheel'
    | '/contact'
    | '/daily-hub'
    | '/destiny-card'
    | '/destiny-cardg'
    | '/dream'
    | '/help'
    | '/life-graph'
    | '/login'
    | '/lottery'
    | '/love-compatibility'
    | '/lucky-colors'
    | '/name-analysis'
    | '/naming'
    | '/phone-analysis'
    | '/plate-analysis'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/siamsi'
    | '/tai-sui'
    | '/tarot'
    | '/terms'
    | '/virtual-shrine'
    | '/wallpaper'
    | '/zodiac'
    | '/admin/articles'
    | '/admin/audit'
    | '/admin/contact'
    | '/admin/dreams'
    | '/admin/help'
    | '/admin/messages'
    | '/admin/users'
    | '/api/admin-login'
    | '/api/admin-session'
    | '/api/admin-users'
    | '/api/articles'
    | '/api/audit-events'
    | '/api/auto-article'
    | '/api/contact-messages'
    | '/api/cron-auto-article'
    | '/api/dashboard'
    | '/api/dreams'
    | '/api/faqs'
    | '/api/leads'
    | '/api/lottery'
    | '/api/reading-history'
    | '/api/site-content'
    | '/api/user-login'
    | '/api/user-register'
    | '/api/user-session'
    | '/articles/$slug'
    | '/dream/$slug'
    | '/profile/history'
    | '/profile/settings'
    | '/tarot/$type'
    | '/admin/'
    | '/articles/'
    | '/dream/'
    | '/profile/'
    | '/tarot/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  AuspiciousCalendarRoute: typeof AuspiciousCalendarRoute
  BaziRoute: typeof BaziRoute
  BrahmaWheelRoute: typeof BrahmaWheelRoute
  ContactRoute: typeof ContactRoute
  DailyHubRoute: typeof DailyHubRoute
  DestinyCardRoute: typeof DestinyCardRoute
  DestinyCardgRoute: typeof DestinyCardgRoute
  DreamRoute: typeof DreamRouteWithChildren
  HelpRoute: typeof HelpRoute
  LifeGraphRoute: typeof LifeGraphRoute
  LoginRoute: typeof LoginRoute
  LotteryRoute: typeof LotteryRoute
  LoveCompatibilityRoute: typeof LoveCompatibilityRoute
  LuckyColorsRoute: typeof LuckyColorsRoute
  NameAnalysisRoute: typeof NameAnalysisRoute
  NamingRoute: typeof NamingRoute
  PhoneAnalysisRoute: typeof PhoneAnalysisRoute
  PlateAnalysisRoute: typeof PlateAnalysisRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SiamsiRoute: typeof SiamsiRoute
  TaiSuiRoute: typeof TaiSuiRoute
  TarotRoute: typeof TarotRouteWithChildren
  TermsRoute: typeof TermsRoute
  VirtualShrineRoute: typeof VirtualShrineRoute
  WallpaperRoute: typeof WallpaperRoute
  ZodiacRoute: typeof ZodiacRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiArticlesRoute: typeof ApiArticlesRoute
  ApiAuditEventsRoute: typeof ApiAuditEventsRoute
  ApiAutoArticleRoute: typeof ApiAutoArticleRoute
  ApiContactMessagesRoute: typeof ApiContactMessagesRoute
  ApiCronAutoArticleRoute: typeof ApiCronAutoArticleRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiDreamsRoute: typeof ApiDreamsRoute
  ApiFaqsRoute: typeof ApiFaqsRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiLotteryRoute: typeof ApiLotteryRoute
  ApiReadingHistoryRoute: typeof ApiReadingHistoryRoute
  ApiSiteContentRoute: typeof ApiSiteContentRoute
  ApiUserLoginRoute: typeof ApiUserLoginRoute
  ApiUserRegisterRoute: typeof ApiUserRegisterRoute
  ApiUserSessionRoute: typeof ApiUserSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zodiac': {
      id: '/zodiac'
      path: '/zodiac'
      fullPath: '/zodiac'
      preLoaderRoute: typeof ZodiacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallpaper': {
      id: '/wallpaper'
      path: '/wallpaper'
      fullPath: '/wallpaper'
      preLoaderRoute: typeof WallpaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-shrine': {
      id: '/virtual-shrine'
      path: '/virtual-shrine'
      fullPath: '/virtual-shrine'
      preLoaderRoute: typeof VirtualShrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot': {
      id: '/tarot'
      path: '/tarot'
      fullPath: '/tarot'
      preLoaderRoute: typeof TarotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-sui': {
      id: '/tai-sui'
      path: '/tai-sui'
      fullPath: '/tai-sui'
      preLoaderRoute: typeof TaiSuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siamsi': {
      id: '/siamsi'
      path: '/siamsi'
      fullPath: '/siamsi'
      preLoaderRoute: typeof SiamsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plate-analysis': {
      id: '/plate-analysis'
      path: '/plate-analysis'
      fullPath: '/plate-analysis'
      preLoaderRoute: typeof PlateAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-analysis': {
      id: '/phone-analysis'
      path: '/phone-analysis'
      fullPath: '/phone-analysis'
      preLoaderRoute: typeof PhoneAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/naming': {
      id: '/naming'
      path: '/naming'
      fullPath: '/naming'
      preLoaderRoute: typeof NamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/name-analysis': {
      id: '/name-analysis'
      path: '/name-analysis'
      fullPath: '/name-analysis'
      preLoaderRoute: typeof NameAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lucky-colors': {
      id: '/lucky-colors'
      path: '/lucky-colors'
      fullPath: '/lucky-colors'
      preLoaderRoute: typeof LuckyColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/love-compatibility': {
      id: '/love-compatibility'
      path: '/love-compatibility'
      fullPath: '/love-compatibility'
      preLoaderRoute: typeof LoveCompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lottery': {
      id: '/lottery'
      path: '/lottery'
      fullPath: '/lottery'
      preLoaderRoute: typeof LotteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-graph': {
      id: '/life-graph'
      path: '/life-graph'
      fullPath: '/life-graph'
      preLoaderRoute: typeof LifeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dream': {
      id: '/dream'
      path: '/dream'
      fullPath: '/dream'
      preLoaderRoute: typeof DreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destiny-cardg': {
      id: '/destiny-cardg'
      path: '/destiny-cardg'
      fullPath: '/destiny-cardg'
      preLoaderRoute: typeof DestinyCardgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destiny-card': {
      id: '/destiny-card'
      path: '/destiny-card'
      fullPath: '/destiny-card'
      preLoaderRoute: typeof DestinyCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-hub': {
      id: '/daily-hub'
      path: '/daily-hub'
      fullPath: '/daily-hub'
      preLoaderRoute: typeof DailyHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brahma-wheel': {
      id: '/brahma-wheel'
      path: '/brahma-wheel'
      fullPath: '/brahma-wheel'
      preLoaderRoute: typeof BrahmaWheelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazi': {
      id: '/bazi'
      path: '/bazi'
      fullPath: '/bazi'
      preLoaderRoute: typeof BaziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auspicious-calendar': {
      id: '/auspicious-calendar'
      path: '/auspicious-calendar'
      fullPath: '/auspicious-calendar'
      preLoaderRoute: typeof AuspiciousCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot/': {
      id: '/tarot/'
      path: '/'
      fullPath: '/tarot/'
      preLoaderRoute: typeof TarotIndexRouteImport
      parentRoute: typeof TarotRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/dream/': {
      id: '/dream/'
      path: '/'
      fullPath: '/dream/'
      preLoaderRoute: typeof DreamIndexRouteImport
      parentRoute: typeof DreamRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tarot/$type': {
      id: '/tarot/$type'
      path: '/$type'
      fullPath: '/tarot/$type'
      preLoaderRoute: typeof TarotTypeRouteImport
      parentRoute: typeof TarotRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/history': {
      id: '/profile/history'
      path: '/history'
      fullPath: '/profile/history'
      preLoaderRoute: typeof ProfileHistoryRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/dream/$slug': {
      id: '/dream/$slug'
      path: '/$slug'
      fullPath: '/dream/$slug'
      preLoaderRoute: typeof DreamSlugRouteImport
      parentRoute: typeof DreamRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/api/user-session': {
      id: '/api/user-session'
      path: '/api/user-session'
      fullPath: '/api/user-session'
      preLoaderRoute: typeof ApiUserSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user-register': {
      id: '/api/user-register'
      path: '/api/user-register'
      fullPath: '/api/user-register'
      preLoaderRoute: typeof ApiUserRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user-login': {
      id: '/api/user-login'
      path: '/api/user-login'
      fullPath: '/api/user-login'
      preLoaderRoute: typeof ApiUserLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-content': {
      id: '/api/site-content'
      path: '/api/site-content'
      fullPath: '/api/site-content'
      preLoaderRoute: typeof ApiSiteContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reading-history': {
      id: '/api/reading-history'
      path: '/api/reading-history'
      fullPath: '/api/reading-history'
      preLoaderRoute: typeof ApiReadingHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lottery': {
      id: '/api/lottery'
      path: '/api/lottery'
      fullPath: '/api/lottery'
      preLoaderRoute: typeof ApiLotteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/faqs': {
      id: '/api/faqs'
      path: '/api/faqs'
      fullPath: '/api/faqs'
      preLoaderRoute: typeof ApiFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dreams': {
      id: '/api/dreams'
      path: '/api/dreams'
      fullPath: '/api/dreams'
      preLoaderRoute: typeof ApiDreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron-auto-article': {
      id: '/api/cron-auto-article'
      path: '/api/cron-auto-article'
      fullPath: '/api/cron-auto-article'
      preLoaderRoute: typeof ApiCronAutoArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact-messages': {
      id: '/api/contact-messages'
      path: '/api/contact-messages'
      fullPath: '/api/contact-messages'
      preLoaderRoute: typeof ApiContactMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auto-article': {
      id: '/api/auto-article'
      path: '/api/auto-article'
      fullPath: '/api/auto-article'
      preLoaderRoute: typeof ApiAutoArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-events': {
      id: '/api/audit-events'
      path: '/api/audit-events'
      fullPath: '/api/audit-events'
      preLoaderRoute: typeof ApiAuditEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/articles': {
      id: '/api/articles'
      path: '/api/articles'
      fullPath: '/api/articles'
      preLoaderRoute: typeof ApiArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-users': {
      id: '/api/admin-users'
      path: '/api/admin-users'
      fullPath: '/api/admin-users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-session': {
      id: '/api/admin-session'
      path: '/api/admin-session'
      fullPath: '/api/admin-session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-login': {
      id: '/api/admin-login'
      path: '/api/admin-login'
      fullPath: '/api/admin-login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dreams': {
      id: '/admin/dreams'
      path: '/dreams'
      fullPath: '/admin/dreams'
      preLoaderRoute: typeof AdminDreamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminDreamsRoute: typeof AdminDreamsRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminContactRoute: AdminContactRoute,
  AdminDreamsRoute: AdminDreamsRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface DreamRouteChildren {
  DreamSlugRoute: typeof DreamSlugRoute
  DreamIndexRoute: typeof DreamIndexRoute
}

const DreamRouteChildren: DreamRouteChildren = {
  DreamSlugRoute: DreamSlugRoute,
  DreamIndexRoute: DreamIndexRoute,
}

const DreamRouteWithChildren = DreamRoute._addFileChildren(DreamRouteChildren)

interface ProfileRouteChildren {
  ProfileHistoryRoute: typeof ProfileHistoryRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileHistoryRoute: ProfileHistoryRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface TarotRouteChildren {
  TarotTypeRoute: typeof TarotTypeRoute
  TarotIndexRoute: typeof TarotIndexRoute
}

const TarotRouteChildren: TarotRouteChildren = {
  TarotTypeRoute: TarotTypeRoute,
  TarotIndexRoute: TarotIndexRoute,
}

const TarotRouteWithChildren = TarotRoute._addFileChildren(TarotRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  AuspiciousCalendarRoute: AuspiciousCalendarRoute,
  BaziRoute: BaziRoute,
  BrahmaWheelRoute: BrahmaWheelRoute,
  ContactRoute: ContactRoute,
  DailyHubRoute: DailyHubRoute,
  DestinyCardRoute: DestinyCardRoute,
  DestinyCardgRoute: DestinyCardgRoute,
  DreamRoute: DreamRouteWithChildren,
  HelpRoute: HelpRoute,
  LifeGraphRoute: LifeGraphRoute,
  LoginRoute: LoginRoute,
  LotteryRoute: LotteryRoute,
  LoveCompatibilityRoute: LoveCompatibilityRoute,
  LuckyColorsRoute: LuckyColorsRoute,
  NameAnalysisRoute: NameAnalysisRoute,
  NamingRoute: NamingRoute,
  PhoneAnalysisRoute: PhoneAnalysisRoute,
  PlateAnalysisRoute: PlateAnalysisRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SiamsiRoute: SiamsiRoute,
  TaiSuiRoute: TaiSuiRoute,
  TarotRoute: TarotRouteWithChildren,
  TermsRoute: TermsRoute,
  VirtualShrineRoute: VirtualShrineRoute,
  WallpaperRoute: WallpaperRoute,
  ZodiacRoute: ZodiacRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiArticlesRoute: ApiArticlesRoute,
  ApiAuditEventsRoute: ApiAuditEventsRoute,
  ApiAutoArticleRoute: ApiAutoArticleRoute,
  ApiContactMessagesRoute: ApiContactMessagesRoute,
  ApiCronAutoArticleRoute: ApiCronAutoArticleRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiDreamsRoute: ApiDreamsRoute,
  ApiFaqsRoute: ApiFaqsRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiLotteryRoute: ApiLotteryRoute,
  ApiReadingHistoryRoute: ApiReadingHistoryRoute,
  ApiSiteContentRoute: ApiSiteContentRoute,
  ApiUserLoginRoute: ApiUserLoginRoute,
  ApiUserRegisterRoute: ApiUserRegisterRoute,
  ApiUserSessionRoute: ApiUserSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
