/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarotRouteImport } from './routes/tarot'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DreamRouteImport } from './routes/dream'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BaziRouteImport } from './routes/bazi'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TarotIndexRouteImport } from './routes/tarot.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TarotTypeRouteImport } from './routes/tarot.$type'
import { Route as ProfileSettingsRouteImport } from './routes/profile.settings'
import { Route as ProfileHistoryRouteImport } from './routes/profile.history'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ApiUserSessionRouteImport } from './routes/api.user-session'
import { Route as ApiUserRegisterRouteImport } from './routes/api.user-register'
import { Route as ApiUserLoginRouteImport } from './routes/api.user-login'
import { Route as ApiSiteContentRouteImport } from './routes/api.site-content'
import { Route as ApiReadingHistoryRouteImport } from './routes/api.reading-history'
import { Route as ApiLeadsRouteImport } from './routes/api.leads'
import { Route as ApiFaqsRouteImport } from './routes/api.faqs'
import { Route as ApiDreamsRouteImport } from './routes/api.dreams'
import { Route as ApiDashboardRouteImport } from './routes/api.dashboard'
import { Route as ApiContactMessagesRouteImport } from './routes/api.contact-messages'
import { Route as ApiArticlesRouteImport } from './routes/api.articles'
import { Route as ApiAdminUsersRouteImport } from './routes/api.admin-users'
import { Route as ApiAdminSessionRouteImport } from './routes/api.admin-session'
import { Route as ApiAdminLoginRouteImport } from './routes/api.admin-login'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminHelpRouteImport } from './routes/admin.help'
import { Route as AdminDreamsRouteImport } from './routes/admin.dreams'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'

const TarotRoute = TarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamRoute = DreamRouteImport.update({
  id: '/dream',
  path: '/dream',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BaziRoute = BaziRouteImport.update({
  id: '/bazi',
  path: '/bazi',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotIndexRoute = TarotIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TarotRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TarotTypeRoute = TarotTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => TarotRoute,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileHistoryRoute = ProfileHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProfileRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const ApiUserSessionRoute = ApiUserSessionRouteImport.update({
  id: '/api/user-session',
  path: '/api/user-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserRegisterRoute = ApiUserRegisterRouteImport.update({
  id: '/api/user-register',
  path: '/api/user-register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserLoginRoute = ApiUserLoginRouteImport.update({
  id: '/api/user-login',
  path: '/api/user-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteContentRoute = ApiSiteContentRouteImport.update({
  id: '/api/site-content',
  path: '/api/site-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadingHistoryRoute = ApiReadingHistoryRouteImport.update({
  id: '/api/reading-history',
  path: '/api/reading-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFaqsRoute = ApiFaqsRouteImport.update({
  id: '/api/faqs',
  path: '/api/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDreamsRoute = ApiDreamsRouteImport.update({
  id: '/api/dreams',
  path: '/api/dreams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactMessagesRoute = ApiContactMessagesRouteImport.update({
  id: '/api/contact-messages',
  path: '/api/contact-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArticlesRoute = ApiArticlesRouteImport.update({
  id: '/api/articles',
  path: '/api/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin-users',
  path: '/api/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin-session',
  path: '/api/admin-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin-login',
  path: '/api/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDreamsRoute = AdminDreamsRouteImport.update({
  id: '/dreams',
  path: '/dreams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/bazi': typeof BaziRoute
  '/contact': typeof ContactRoute
  '/dream': typeof DreamRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/tarot': typeof TarotRouteWithChildren
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/dreams': typeof AdminDreamsRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-session': typeof ApiAdminSessionRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/articles': typeof ApiArticlesRoute
  '/api/contact-messages': typeof ApiContactMessagesRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/dreams': typeof ApiDreamsRoute
  '/api/faqs': typeof ApiFaqsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/reading-history': typeof ApiReadingHistoryRoute
  '/api/site-content': typeof ApiSiteContentRoute
  '/api/user-login': typeof ApiUserLoginRoute
  '/api/user-register': typeof ApiUserRegisterRoute
  '/api/user-session': typeof ApiUserSessionRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/tarot/$type': typeof TarotTypeRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/tarot/': typeof TarotIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/bazi': typeof BaziRoute
  '/contact': typeof ContactRoute
  '/dream': typeof DreamRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/dreams': typeof AdminDreamsRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-session': typeof ApiAdminSessionRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/articles': typeof ApiArticlesRoute
  '/api/contact-messages': typeof ApiContactMessagesRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/dreams': typeof ApiDreamsRoute
  '/api/faqs': typeof ApiFaqsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/reading-history': typeof ApiReadingHistoryRoute
  '/api/site-content': typeof ApiSiteContentRoute
  '/api/user-login': typeof ApiUserLoginRoute
  '/api/user-register': typeof ApiUserRegisterRoute
  '/api/user-session': typeof ApiUserSessionRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/tarot/$type': typeof TarotTypeRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/tarot': typeof TarotIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/bazi': typeof BaziRoute
  '/contact': typeof ContactRoute
  '/dream': typeof DreamRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/tarot': typeof TarotRouteWithChildren
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/dreams': typeof AdminDreamsRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-session': typeof ApiAdminSessionRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/articles': typeof ApiArticlesRoute
  '/api/contact-messages': typeof ApiContactMessagesRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/dreams': typeof ApiDreamsRoute
  '/api/faqs': typeof ApiFaqsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/reading-history': typeof ApiReadingHistoryRoute
  '/api/site-content': typeof ApiSiteContentRoute
  '/api/user-login': typeof ApiUserLoginRoute
  '/api/user-register': typeof ApiUserRegisterRoute
  '/api/user-session': typeof ApiUserSessionRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/tarot/$type': typeof TarotTypeRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/tarot/': typeof TarotIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/articles'
    | '/bazi'
    | '/contact'
    | '/dream'
    | '/help'
    | '/login'
    | '/profile'
    | '/register'
    | '/tarot'
    | '/admin/articles'
    | '/admin/contact'
    | '/admin/dreams'
    | '/admin/help'
    | '/admin/messages'
    | '/admin/users'
    | '/api/admin-login'
    | '/api/admin-session'
    | '/api/admin-users'
    | '/api/articles'
    | '/api/contact-messages'
    | '/api/dashboard'
    | '/api/dreams'
    | '/api/faqs'
    | '/api/leads'
    | '/api/reading-history'
    | '/api/site-content'
    | '/api/user-login'
    | '/api/user-register'
    | '/api/user-session'
    | '/articles/$slug'
    | '/profile/history'
    | '/profile/settings'
    | '/tarot/$type'
    | '/admin/'
    | '/articles/'
    | '/profile/'
    | '/tarot/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-login'
    | '/bazi'
    | '/contact'
    | '/dream'
    | '/help'
    | '/login'
    | '/register'
    | '/admin/articles'
    | '/admin/contact'
    | '/admin/dreams'
    | '/admin/help'
    | '/admin/messages'
    | '/admin/users'
    | '/api/admin-login'
    | '/api/admin-session'
    | '/api/admin-users'
    | '/api/articles'
    | '/api/contact-messages'
    | '/api/dashboard'
    | '/api/dreams'
    | '/api/faqs'
    | '/api/leads'
    | '/api/reading-history'
    | '/api/site-content'
    | '/api/user-login'
    | '/api/user-register'
    | '/api/user-session'
    | '/articles/$slug'
    | '/profile/history'
    | '/profile/settings'
    | '/tarot/$type'
    | '/admin'
    | '/articles'
    | '/profile'
    | '/tarot'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/articles'
    | '/bazi'
    | '/contact'
    | '/dream'
    | '/help'
    | '/login'
    | '/profile'
    | '/register'
    | '/tarot'
    | '/admin/articles'
    | '/admin/contact'
    | '/admin/dreams'
    | '/admin/help'
    | '/admin/messages'
    | '/admin/users'
    | '/api/admin-login'
    | '/api/admin-session'
    | '/api/admin-users'
    | '/api/articles'
    | '/api/contact-messages'
    | '/api/dashboard'
    | '/api/dreams'
    | '/api/faqs'
    | '/api/leads'
    | '/api/reading-history'
    | '/api/site-content'
    | '/api/user-login'
    | '/api/user-register'
    | '/api/user-session'
    | '/articles/$slug'
    | '/profile/history'
    | '/profile/settings'
    | '/tarot/$type'
    | '/admin/'
    | '/articles/'
    | '/profile/'
    | '/tarot/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  BaziRoute: typeof BaziRoute
  ContactRoute: typeof ContactRoute
  DreamRoute: typeof DreamRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  TarotRoute: typeof TarotRouteWithChildren
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiArticlesRoute: typeof ApiArticlesRoute
  ApiContactMessagesRoute: typeof ApiContactMessagesRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiDreamsRoute: typeof ApiDreamsRoute
  ApiFaqsRoute: typeof ApiFaqsRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiReadingHistoryRoute: typeof ApiReadingHistoryRoute
  ApiSiteContentRoute: typeof ApiSiteContentRoute
  ApiUserLoginRoute: typeof ApiUserLoginRoute
  ApiUserRegisterRoute: typeof ApiUserRegisterRoute
  ApiUserSessionRoute: typeof ApiUserSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarot': {
      id: '/tarot'
      path: '/tarot'
      fullPath: '/tarot'
      preLoaderRoute: typeof TarotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dream': {
      id: '/dream'
      path: '/dream'
      fullPath: '/dream'
      preLoaderRoute: typeof DreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazi': {
      id: '/bazi'
      path: '/bazi'
      fullPath: '/bazi'
      preLoaderRoute: typeof BaziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot/': {
      id: '/tarot/'
      path: '/'
      fullPath: '/tarot/'
      preLoaderRoute: typeof TarotIndexRouteImport
      parentRoute: typeof TarotRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tarot/$type': {
      id: '/tarot/$type'
      path: '/$type'
      fullPath: '/tarot/$type'
      preLoaderRoute: typeof TarotTypeRouteImport
      parentRoute: typeof TarotRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/history': {
      id: '/profile/history'
      path: '/history'
      fullPath: '/profile/history'
      preLoaderRoute: typeof ProfileHistoryRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/api/user-session': {
      id: '/api/user-session'
      path: '/api/user-session'
      fullPath: '/api/user-session'
      preLoaderRoute: typeof ApiUserSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user-register': {
      id: '/api/user-register'
      path: '/api/user-register'
      fullPath: '/api/user-register'
      preLoaderRoute: typeof ApiUserRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user-login': {
      id: '/api/user-login'
      path: '/api/user-login'
      fullPath: '/api/user-login'
      preLoaderRoute: typeof ApiUserLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-content': {
      id: '/api/site-content'
      path: '/api/site-content'
      fullPath: '/api/site-content'
      preLoaderRoute: typeof ApiSiteContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reading-history': {
      id: '/api/reading-history'
      path: '/api/reading-history'
      fullPath: '/api/reading-history'
      preLoaderRoute: typeof ApiReadingHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/faqs': {
      id: '/api/faqs'
      path: '/api/faqs'
      fullPath: '/api/faqs'
      preLoaderRoute: typeof ApiFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dreams': {
      id: '/api/dreams'
      path: '/api/dreams'
      fullPath: '/api/dreams'
      preLoaderRoute: typeof ApiDreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact-messages': {
      id: '/api/contact-messages'
      path: '/api/contact-messages'
      fullPath: '/api/contact-messages'
      preLoaderRoute: typeof ApiContactMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/articles': {
      id: '/api/articles'
      path: '/api/articles'
      fullPath: '/api/articles'
      preLoaderRoute: typeof ApiArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-users': {
      id: '/api/admin-users'
      path: '/api/admin-users'
      fullPath: '/api/admin-users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-session': {
      id: '/api/admin-session'
      path: '/api/admin-session'
      fullPath: '/api/admin-session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-login': {
      id: '/api/admin-login'
      path: '/api/admin-login'
      fullPath: '/api/admin-login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dreams': {
      id: '/admin/dreams'
      path: '/dreams'
      fullPath: '/admin/dreams'
      preLoaderRoute: typeof AdminDreamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminDreamsRoute: typeof AdminDreamsRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRoute,
  AdminContactRoute: AdminContactRoute,
  AdminDreamsRoute: AdminDreamsRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface ProfileRouteChildren {
  ProfileHistoryRoute: typeof ProfileHistoryRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileHistoryRoute: ProfileHistoryRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface TarotRouteChildren {
  TarotTypeRoute: typeof TarotTypeRoute
  TarotIndexRoute: typeof TarotIndexRoute
}

const TarotRouteChildren: TarotRouteChildren = {
  TarotTypeRoute: TarotTypeRoute,
  TarotIndexRoute: TarotIndexRoute,
}

const TarotRouteWithChildren = TarotRoute._addFileChildren(TarotRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  BaziRoute: BaziRoute,
  ContactRoute: ContactRoute,
  DreamRoute: DreamRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RegisterRoute: RegisterRoute,
  TarotRoute: TarotRouteWithChildren,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiArticlesRoute: ApiArticlesRoute,
  ApiContactMessagesRoute: ApiContactMessagesRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiDreamsRoute: ApiDreamsRoute,
  ApiFaqsRoute: ApiFaqsRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiReadingHistoryRoute: ApiReadingHistoryRoute,
  ApiSiteContentRoute: ApiSiteContentRoute,
  ApiUserLoginRoute: ApiUserLoginRoute,
  ApiUserRegisterRoute: ApiUserRegisterRoute,
  ApiUserSessionRoute: ApiUserSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
